# -*- coding: utf-8 -*-
"""Assignment5ENG220

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/166ubelKvKHJ4VOeQCoYetNGieTB3QeOs
"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# 
# # Title for the app
# st.title("Type your name")
# 
# # Create a text input widget
# name = st.text_input("Enter your name")
# 
# # Display the user's input after they submit their name
# if name:
#     st.write(f"Your name is {name}")
#